x-logging: &logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:${SQLSERVER_VERSION}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "${SQLSERVER_PASSWORD}", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      SA_PASSWORD: ${SQLSERVER_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - 1433:1433
    volumes:
      - sqlserver-data:/var/opt/mssql
    logging: *logging
    networks:
      - keycloak

  db-init:
    build:
      context: .
      dockerfile: Dockerfile.init
    environment:
      SQLSERVER_PASSWORD: ${SQLSERVER_PASSWORD}
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - keycloak

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile-keycloak
    restart: unless-stopped
    ports:
    - ${KC_PORT}:8080
    - 8443:8443
    - 9000:9000
    volumes:
    - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json:ro
    logging: *logging
    networks:
      - keycloak

networks:
  keycloak:
    driver: bridge
