# Stage 1: Build Keycloak
FROM quay.io/keycloak/keycloak:25.0.1 as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=mssql

WORKDIR /opt/keycloak
# For demonstration purposes only, please make sure to use proper certificates in production instead

# Add MSSQL JDBC driver
ADD --chown=keycloak:keycloak --chmod=644 https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/9.4.1.jre11/mssql-jdbc-9.4.1.jre11.jar /opt/keycloak/providers/mssql-jdbc-9.2.1.jre11.jar
ADD  --chown=keycloak:keycloak --chmod=644 https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/9.4.1.jre11/mssql-jdbc-9.4.1.jre11.jar /opt/jboss/keycloak/modules/system/layers/base/com/microsoft/sqlserver/main/mssql-jdbc.jar
# Add the module.xml file to configure the MSSQL module
ADD module.xml /opt/jboss/keycloak/modules/system/layers/base/com/microsoft/sqlserver/main/

# copy certs files
COPY certs/ /opt/keycloak/certs/

RUN /opt/keycloak/bin/kc.sh build

# Stage 2: Final image
FROM quay.io/keycloak/keycloak:25.0.1
COPY --from=builder /opt/keycloak/ /opt/keycloak/



# ENV for Keycloak
ENV KC_PROXY=none
ENV KC_LOG_LEVEL=INFO
ENV KC_CACHE=local
ENV KC_CACHE_STACK=stack
ENV KC_FEATURES=preview
ENV KC_HTTP_RELATIVE_PATH=/
ENV KC_HOSTNAME_STRICT=false
#ENV KC_HOSTNAME_STRICT_BACKCHANNEL=false
# ENV KC_PROXY_HEADERS=xforwarded
# ENV KC_HOSTNAME_ADMIN=localhost
# ENV KC_HOSTNAME_FRONTEND=localhost
ENV KC_LOG_CONSOLE_COLOR=true



ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--optimized" , "--hostname-strict=false", "--https-certificate-file=/opt/keycloak/certs/keycloak.pem", "--https-certificate-key-file=/opt/keycloak/certs/keycloakkey.pem"]