# Stage 1: Build Keycloak
FROM quay.io/keycloak/keycloak:25.0.1 as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=mssql

WORKDIR /opt/keycloak
# For demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
RUN /opt/keycloak/bin/kc.sh build

# Stage 2: Final image
FROM quay.io/keycloak/keycloak:25.0.1
COPY --from=builder /opt/keycloak/ /opt/keycloak/



# ENV for Keycloak
ENV KC_HTTP_PORT=8080
ENV KC_HTTPS_PORT=8443
ENV KC_PROXY=none
ENV KC_LOG_LEVEL=INFO
ENV KC_CACHE=local
ENV KC_CACHE_STACK=stack
ENV KC_FEATURES=preview
ENV KC_HTTP_RELATIVE_PATH=/
ENV KC_HOSTNAME_STRICT=false
ENV KC_HOSTNAME_STRICT_BACKCHANNEL=false
# ENV KC_PROXY_HEADERS=xforwarded
# ENV KC_HOSTNAME_ADMIN=localhost
# ENV KC_HOSTNAME_FRONTEND=localhost
ENV KC_LOG_CONSOLE_COLOR=true


# Add MSSQL JDBC driver
ADD --chown=keycloak:keycloak --chmod=644 https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/9.4.1.jre11/mssql-jdbc-9.4.1.jre11.jar /opt/keycloak/providers/mssql-jdbc-9.2.1.jre11.jar
ADD  --chown=keycloak:keycloak --chmod=644 https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/9.4.1.jre11/mssql-jdbc-9.4.1.jre11.jar /opt/jboss/keycloak/modules/system/layers/base/com/microsoft/sqlserver/main/mssql-jdbc.jar
# Add the module.xml file to configure the MSSQL module
ADD module.xml /opt/jboss/keycloak/modules/system/layers/base/com/microsoft/sqlserver/main/

# Expose Keycloak ports
EXPOSE 8080 8443 9000

# Context: RUN the build command
RUN /opt/keycloak/bin/kc.sh build

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--optimized" , "--hostname-strict=false",  "--features=admin2,hostname-v2,docker,recovery-codes"]