FROM mcr.microsoft.com/mssql-tools

COPY .init/create_database.sql /scripts/create_database.sql
COPY entrypoint.sh /scripts/entrypoint.sh

RUN chmod +x /scripts/entrypoint.sh

ENTRYPOINT ["/scripts/entrypoint.sh"]