version: '3.8'

x-logging: &logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:${SQLSERVER_VERSION}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "${SQLSERVER_PASSWORD}", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      SA_PASSWORD: ${SQLSERVER_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - 1433:1433
    volumes:
      - sqlserver-data:/var/opt/mssql
    logging: *logging
    networks:
      - keycloak

  db-init:
    build:
      context: .
      dockerfile: Dockerfile.init
    environment:
      SQLSERVER_PASSWORD: ${SQLSERVER_PASSWORD}
    depends_on:
      - sqlserver
    networks:
      - keycloak

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile-keycloak
    restart: unless-stopped
    environment:
       DB_VENDOR: "mssql"
       KC_DB_USERNAME: "sa"
       KC_DB_PASSWORD: "${SQLSERVER_PASSWORD}"
       KC_DB_URL: "jdbc:sqlserver://sqlserver:1433;databaseName=keycloak;encrypt=false;trustServerCertificate=true"
       QUARKUS_DATASOURCE_JDBC_URL: "jdbc:sqlserver://sqlserver:1433;databaseName=keycloak;encrypt=false;trustServerCertificate=true;loginTimeout=30"
       KC_METRICS_ENABLED: "true"
       KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
       KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
       KC_HOSTNAME: ${KC_HOSTNAME}
       KC_HOSTNAME_ADMIN: ${KC_HOSTNAME}
       KC_HOSTNAME_FRONTEND: ${KC_HOSTNAME}
    depends_on:
      - sqlserver
    ports:
    - ${KC_PORT}:8080
    - 8443:8443
    - 9000:9000
    logging: *logging
    networks:
      - keycloak

volumes:
  sqlserver-data:

networks:
  keycloak:
    driver: bridge
